version: '3'

services:
  db:
    image: mysql:5.7
    container_name: exampleApi
    restart: always
    ports:
      - "3304:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9090:90'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
